# .github/workflows/deploy.yml
name: CI/CD Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          IMAGE_NAME=${{ vars.DOCKERHUB_USERNAME }}/nestjs-realworld-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/nestjs-realworld-app:latest
            docker compose up -d